--$ java -jar h2-2.1.210.jar

DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES (TYPEID INT, TYPE CHAR(20));
SELECT * FROM  TYPES;



SELECT DISTINCT TYPE1 FROM POKEDEX ORDER BY TYPE1 ASC;
--ALTER TABLE TYPES ADD TYPEID INT;