--$ java -jar h2-2.1.210.jar

--See all tables
SELECT * FROM  TYPES;
SELECT * FROM NUMBERS;
SELECT * FROM POKEMON;
SELECT * FROM POKEDEX;

--DROP NUMBERS AND TYPES
DROP TABLE NUMBERS IF EXISTS;
DROP TABLE TYPES IF EXISTS;

--CREATE DISTINCT
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES AS SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;

--SELECT DISTINCT
SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;

--THE CREATING OF POKEMON TABLE, NORMALIZED
DROP TABLE POKEMON IF EXISTS;
CREATE TABLE POKEMON AS SELECT * FROM POKEDEX; 
ALTER TABLE POKEMON ADD COLUMN (TYPE1ID INTEGER);
ALTER TABLE POKEMON ADD FOREIGN KEY (TYPE1ID) REFERENCES TYPES(TYPEID);
ALTER TABLE POKEMON ADD COLUMN (TYPE2ID INTEGER);
ALTER TABLE POKEMON ADD FOREIGN KEY (TYPE2ID) REFERENCES TYPES(TYPEID);
UPDATE POKEMON SET TYPE1ID=(SELECT TYPEID FROM TYPES WHERE TYPES.TYPENAME  = TYPE1);
UPDATE POKEMON SET TYPE2ID=(SELECT TYPEID FROM TYPES WHERE TYPES.TYPENAME  = TYPE2);
ALTER TABLE POKEMON DROP COLUMN TYPE1;
ALTER TABLE POKEMON DROP COLUMN TYPE2;

--THE CREATING OF TYPES TABLE
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES (TYPEID INT PRIMARY KEY, TYPENAME CHAR(50));
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (1,null);
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (2,'Bug');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (3,'Dark');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (4,'Dragon');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (5,'Electric');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (6,'Fairy');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (7,'Fighting');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (8,'Fire');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (9,'Flying');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (10,'Ghost');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (11,'Grass');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (12,'Ground');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (13,'Ice');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (14,'Normal');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (15,'Poison');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (16,'Psychic');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (17,'Rock');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (18,'Steel');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (19,'Water');

--CREATE BACKUP
CREATE TABLE POKEDEXBU AS SELECT * FROM POKEDEX 


SELECT TYPEID FROM NUMBERS AND TYPE2 FROM TYPES; 

--Update test(doesn't work)
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES(TYPEID INT, TYPENAME CHAR(50)) AS SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;
UPDATE TYPES SET TYPEID = 1,2,3,4,5,6,7,8,9,10,11,12,13;

--See Normalized table as whole
SELECT POKEDEX.ID, POKEDEX.NAME, TYPES.TYPENAME
FROM POKEDEX
JOIN TYPES 
ON POKEDEX.TYPE1ID = TYPES.TYPEID
JOIN TYPES 
ON POKEDEX.TYPE2ID = TYPES.TYPEID
ORDER BY POKEDEX.ID ASC;


--ALTER POKEDEX
--ALTER TABLE POKEDEX DROP TYPE1ID, TYPE2ID;
ALTER TABLE POKEDEX ADD (
TYPE1ID INT FOREIGN KEY, TYPE2ID INT FOREIGN KEY)

--update pokedex
UPDATE POKEDEX SET TYPE1ID = TYPES.TYPEID 
WHERE POKEDEX.TYPE1 = TYPES.TYPENAME;

--See Normalized table as whole
SELECT POKEDEX.ID, POKEDEX.NAME, TYPES.TYPENAME
FROM POKEDEX
JOIN TYPES 
ON POKEDEX.TYPE1ID = TYPES.TYPEID
--JOIN TYPES 
--ON POKEDEX.TYPE2ID = TYPES.TYPEID
ORDER BY POKEDEX.ID ASC;

--CREATE LINKS
--CREATE TABLE POKEMON (ID INTEGER PRIMARY KEY, NAME VARCHAR, TYPE1 INTEGER, FOREIGN KEY (TYPE1) REFERENCES TYPES(ID));
ALTER TABLE POKEMON ADD COLUMN (TYPE1ID INTEGER);
ALTER TABLE POKEMON ADD FOREIGN KEY (TYPE1ID) REFERENCES TYPES(TYPEID)

ALTER TABLE POKEMON ADD COLUMN (TYPE2ID INTEGER)
ALTER TABLE POKEMON ADD FOREIGN KEY (TYPE2ID) REFERENCES TYPES(TYPEID)

ALTER TABLE TYPES ADD PRIMARY KEY TYPEID 
--JUNK
DROP TABLE NUMBERS IF EXISTS;
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES AS SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;
INSERT INTO TYPES (TYPEID) FROM NUMBERS;
CREATE TABLE TYPES (TYPEID INT);
ALTER TABLE TYPES ADD TYPEID INT;
INSERT INTO TYPES (TYPEID) VALUES (1);
INSERT INTO TYPES (TYPEID) VALUES (2);
