--$ java -jar h2-2.1.210.jar

--See all tables
SELECT * FROM  TYPES;
SELECT * FROM NUMBERS;
SELECT * FROM POKEMON;
SELECT * FROM POKEDEX;

--DROP NUMBERS AND TYPES
DROP TABLE NUMBERS IF EXISTS;
DROP TABLE TYPES IF EXISTS;

--CREATE DISTINCT
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES AS SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;

--SELECT DISTINCT
SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;

--CREATE TYPES TABLE
CREATE TABLE TYPES (TYPEID INT, TYPENAME CHAR(50));
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (1,null);
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (2,'Bug');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (3,'Dark');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (4,'Dragon');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (5,'Electric');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (6,'Fairy');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (7,'Fighting');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (8,'Fire');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (9,'Flying');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (10,'Ghost');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (11,'Grass');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (12,'Ground');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (13,'Ice');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (14,'Normal');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (15,'Poison');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (16,'Psychic');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (17,'Rock');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (18,'Steel');
INSERT INTO TYPES (TYPEID, TYPENAME) VALUES (19,'Water');

--CREATE BACKUP
CREATE TABLE POKEDEXBU AS SELECT * FROM POKEDEX 


SELECT TYPEID FROM NUMBERS AND TYPE2 FROM TYPES; 





--JUNK
DROP TABLE NUMBERS IF EXISTS;
DROP TABLE TYPES IF EXISTS;
CREATE TABLE TYPES AS SELECT DISTINCT TYPE2 FROM POKEDEX ORDER BY TYPE2 ASC;
INSERT INTO TYPES (TYPEID) FROM NUMBERS;
CREATE TABLE TYPES (TYPEID INT);
ALTER TABLE TYPES ADD TYPEID INT;
INSERT INTO TYPES (TYPEID) VALUES (1);
INSERT INTO TYPES (TYPEID) VALUES (2);